### ISSUE TITLE
FAIL - Application at context path /constellation-1.0.5 could not be started

### ISSUE THREAD

**Issue by ghaspaer** [Geomatys/constellation#5]
from Tomcat Web Application Manager, I have the following message:
FAIL - Application at context path /constellation-1.0.5 could not be started
---------------------------------
I'm using debian 8 + tomcat7

**Comment by amanin** [comment]
Hi,

To help you, we will need more information please : 
 - What is your java version ? A JRE 7 at least is required.
 - Is there errors in your "catalina.out" or "localhost.log" files ?

Also, can you confirm you downloaded war file from here : 
http://constellation-sdi.org/download/constellation-1.0.5.war

One last question, did you tried to copy war file directly under $CATALINA_HOME/webapps folder instead of using tomcat manager ?

Regards,

**Comment by ghaspaer** [comment]
Hi,
* I have Java7.
* I've downloaded the war the right place.
* I've copied the war directly to the webapp directory
* Here's the file catalina.out  http://pastebin.com/MS42ytfe

Regards,

**Comment by cheleb** [comment]
Hi,


   1. Caused by: java.nio.file.AccessDeniedException:
   /usr/share/tomcat7/.constellation


The $HOME of the user who run tomcat is is not writable.

Best regards,
Olivier


On Mon, Jun 29, 2015 at 11:26 PM, Ghaspaer <notifications@github.com> wrote:

> Hi,
>
>    - I have Java7.
>    - I've downloaded the war the right place.
>    - I've copied the war directly to the webapp directory
>    - Here's the file catalina.out http://pastebin.com/MS42ytfe
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geomatys/constellation/issues/5#issuecomment-116850756>
> .
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -
