### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by julien84** [Geomatys/constellation#6]
Hello,
Would you have a documentation to install Constellation SDI on Windows ?
I found a link but this one is broken : http://www.constellation-sdi.org/fr/aide/lancement-appli.html

I tried to deploy the solution on Tomcat but I have errors in context path (http://pastebin.com/e5JreaCS). Maybe I have missed some tricks specific to Windows ?
Thanks !

Regards, 
Julien

**Comment by qboileau** [comment]
Hi @julien84, 
you can found updated Constellation documentation [here](http://www.constellation-sdi.org/en/doc/installation.html)

Can you provide us more informations about your platform (Java and Tomcat version) ?
Can you also give the content of tomcat log files ? Especially **localhost.log**. They should be into **logs** directory next to **webapps**. 

Did you create **setenv.bat** file into Tomcat **bin** directory with your specific configuration ? If this file exist, can you print his content here ? You can found more information about the content of the setenv.bat file into Constellation [documenation](http://www.constellation-sdi.org/en/doc/installation.html) and Oracle [documentation](https://docs.oracle.com/cd/E40520_01/integrator.311/integrator_install/src/cli_ldi_server_config.html)

Also, your log say that the currently deployed war is named `cstl-sdi-1.1.1 (2).war`. I don't think this would be a problem for Tomcat, but it's strongly recommended to remove space and special characters in war name. Because this name will become your application context path.

Regards,
Quentin

**Comment by desruisseaux** [comment]
This project is archived and replaced by [Examind-community](https://github.com/Geomatys/examind-community).
