### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by fredmorin** [Geomatys/constellation#7]
I just learned about the existence of constellation, I tried the online demo and thought it was great so I had to install a local instance to make further tests. I am having some issues getting constellation to work. I hope I can bring a small contribution by improving documentation on how to setup constellation on Ubuntu in the near future. In the meantime, I documented my procedure and issues here:

The page located at http://www.constellation-sdi.org/fr/demo.html mentions that we can download a virtual machine, unfortunately I could not figure out where to find the VM, so I tried to setup a Ubuntu VM.

I installed the pre-requisites using apt-get commands:
sudo apt-get update
sudo apt-get install tomcat7
sudo apt-get-install postgresql-9.3-postgis-2.1
sudo apt-get install software-properties-common
sudo -E add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get-install oracle-java7-installer

This is not part of constellation instruction, but I edited tomcat configuration: /etc/default/tomcat7
JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Xmx512m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC"

I created the postgres database:
sudo -u postgresql psql
CREATE USER cstl WITH ENCRYPTED PASSWORD 'admin';
CREATE DATABASE constellation OWNER cstl ENCODING 'UTF8'; 

I do not quite understand the part of the documentation related to the configuration of tomcat where it states to create a setenv.sh file in Tomcat's bin folder. I created the file, but I'd like to understand the reasons why I have to create a shell script here... Should I allow execution right on this file?
http://www.constellation-sdi.org/fr/doc/installation.html#deployment

Finally I deployed cstl-sdi-1.1.2.war in /var/lib/tomcat7/webapps and restarted tomcat
sudo service tomcat7 restart

The webapp fails to start, the log states: Could not create: /usr/share/tomcat7/.constellation

[ERROR] o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.constellation.admin.ConfigurationServiceInit#0' defined in class path resource [spring/constellation-context.xml]: Invocation of init method failed; nested exception is org.constellation.configuration.ConfigurationRuntimeException: Could not create: /usr/share/tomcat7/.constellation

I manually created the .constellation folder and gave full rights 777 to it.Then restarted tomcat and the webapp successfully starts. This is far from the ideal solution, I'd like to know why constellation tries to write to this folder, is it configurable?

At this point, the webapp starts and the web page loads. unfortunately I am not able to login.I looked at the logs again and it shows:

org.apache.catalina.loader.WebappClassLoader validateJar           File
INFO: validateJarFile(/var/lib/tomcat7/webapps/constellation/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Dec 17, 2015 1:45:53 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.geotoolkit.util.FileUtilities.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.

Then the REST API Application fails to start

[INFO ] org.constellation.ws.rs - Starting Rest API Application
[WARN ] o.s.w.s.s.t.h.DefaultSockJsService - Failed to create default WebSocketTra
java.lang.IllegalStateException: No suitable default RequestUpgradeStrategy found

**Comment by fredmorin** [comment]
Another observation related with pluign. I noticed the Login button tries to post to a url using the cstlUrl variable. In my case, the cstlUrl value is "http://constellation/" which does not work. I modified the variable value at runtime for "http://constellation:8080/constellation/" and login worked.
Of course, I now get many other errors related with the REST service since all other request keep trying to access http://constellation/api/... 

Looks like there is some sort of issue with how this cstlUrl variable is set.

**Comment by qboileau** [comment]
Hi @fredmorin, 
first thanks for using Constellation-SDI and willing to contribute on the project.

The mentioned VM on http://www.constellation-sdi.org/fr/demo.html page was an error and is now removed.

About Tomcat configuration we usually install Tomcat from binary distribution avaible on Apache Tomcat website. From scratch, Tomcat allow configuration override using a **setenv.sh**(with +x permissions) file in **bin/** directory. This is what Constellation SDI describe.

In your case, with an installation from Ubuntu repositories a lot of things are done. Binaries are installed in /usr/share/tomcat7, variables files like webapps are installed in /var/lib/tomcat7 and configuration override is located in /etc/default/tomcat7. So in your case you don't have to bother about setenv.sh file you can tune your tomcat directly form /etc/default/tomcat7.

About your first start attempt when logs states Could not create: /usr/share/tomcat7/.constellation. This error is due to "tomcat" user home directory located in /usr/share/tomcat7/ directory that belong to root user. Constellation use defined "user.home" java system property to store configurations, data and logs in a .constellation directory. 
Instead of set 777 rights to /usr/share/tomcat7 diretory, you can set "user.home" directory into /etc/default/tomcat7 JAVA_OPTS parts.

```
JAVA_OPTS="${JAVA_OPTS} -Duser.home=<new_location>"
```
This directory should be accessible to tomcat unix group.
Note "cstl.home" property should also work.


Or another solution may be to change user used to run tomcat program to use your current user. Fortunatly this seems to be easily configurable from /etc/default/tomcat7 file.
```
# Run Tomcat as this user ID. Not setting this or leaving it blank will use the
# default of tomcat7.
TOMCAT7_USER=<your_user>

# Run Tomcat as this group ID. Not setting this or leaving it blank will use
# the default of tomcat7.
TOMCAT7_GROUP=<your_user_group>

```

About your cstlUrl issue, i'm not sure about what's is happening here. Are you accessing webapp from outside of your VM ? I think this is a configuration of tomcat7 installer that "hide" port number and webapp name.
Either way you can configure cstlUrl variable using another startup java option should do the trick.
```
JAVA_OPTS="${JAVA_OPTS} -Dcstl.url=http://constellation:8080/constellation/"
```

I guess your domain name is constellation instead of localhost, but be carefull about your application context path, it should be the war file name 
Note : /constellation/ means you have constellation.war in your webapps directory, if you have cstl-sdi-112.war then the context path will be /cstl-sdi-112/

**Comment by fredmorin** [comment]
Thanks for your reply! 

I was able to get constellation running on my environment, I used the setenv.sh and added the -Dcstl.url=http://constellation:8080/constellation/ configuration to it. I will try out constellation, I already see a lot of value to it.

I noticed on the following page that there might be a way to import data from a database, I do not have access to this feature. Is it missing from constellation 1.1.2 or do I have to enable it through some configuration? http://www.constellation-sdi.org/fr/doc/gestion-donnees.html I have a database with a huge set of data and I would like to see if I could connect to it from constellation.

**Comment by qboileau** [comment]
Glad to know that your constellation run on your environment. 

About data import from database, sorry but French documentation was not up-to-date. This functionality wasn't stable enough (JDBC connections not always released) to be avalaible out-of-the-box. Database import will be avalaible in future Constellation-SDI release.

But if you want to try this functionality you can enable it by uncomment some javascript. Here is the procedure : 
- stop your Tomcat server
- edit `/var/lib/tomcat7/webapps/constellation/js/cstl.js` file
- uncomment last entry of `self.addDataWays` variable and save it.

You should have somthing like this : 
```javascript
self.addDataWays = [
            {
                idHTML: 'uploadchoice',
                name: 'localFile',
                translateKey: 'label.file.local',
                defaultTranslateValue: 'Local file',
                bindFunction: function() { startDataImport('local', 'step1DataLocal', true); }
            },
            {
                idHTML: 'filesystemchoice',
                name: 'serverFile',
                translateKey: 'label.file.server',
                defaultTranslateValue: 'Server file',
                bindFunction: function() { startDataImport('server', 'step1DataServer', true); }
            },
            {
                idHTML: 'dbchoice',
                name: 'database',
                translateKey: 'label.file.db',
                defaultTranslateValue: 'Database',
                bindFunction: function() { startDataImport('database', 'step1Database', true); }
            }
        ];
``` 
- restart your Tomcat
And now you should have another option in "Add Data" dropdown.

Note this database import only work with vector PostGIS data.

**Comment by desruisseaux** [comment]
This project is archived and replaced by [Examind-community](https://github.com/Geomatys/examind-community).
